inherit_from: .rubocop_todo.yml

AllCops:
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - db/migrate/*
    - vendor/**/

  # Rails向けのRails copsを実行。"rubocop -R"と同じ
  Rails:
    enabled: true

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "Prefer single-quoted strings when you don't need string interpolation or special symbols."を無効
Style/StringLiterals:
  Enabled: false

# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false

#'frozen_string_literal: true'を無効
Style/FrozenStringLiteralComment:
  Enabled: false

#日本語許可
Style/AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 11

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'

Metrics/PerceivedComplexity:
  Max: 11

Metrics/AbcSize:
  Max: 43

Style/GuardClause:
  Exclude:
    - 'app/controllers/missions_controller.rb'
    